name: lint_python
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  lint_python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.9.0-rc.1]  # [2.7, 3.5, 3.6, 3.7, 3.8, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install codespell flake8 pytest
      - run: codespell --quiet-level=2 || true  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pip install -r requirements.txt || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
